### ISSUE TITLE
Mixed tabbed/stacked workspaces.

### ISSUE THREAD

**Issue by ra-om** [nikola-kocic/i3-switch-tabs#4]
The program works great as long as you only have one tabbed container in a workspace, otherwise, it focuses the next parent, wherever it may be, instead of the next tabs within the initial container . I couldn't figure out from looking at the code what I'd need to change to restrict changing to the current container's tabs, can you help me here, please?

**Comment by ra-om** [comment]
Well, it started working correctly after a few reboots, seems it was a problem on my end. Nice project.

**Comment by nikola-kocic** [comment]
Hi, thanks for report. I also noticed the program misbehaving in some cases.
I released new version (v0.1.4) which should be more resilient, so please try it out :)

**Comment by ra-om** [comment]
New version working pretty good, Thank you!
